<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_638df0fc619fa',
	'title' => 'Template / Governance - Corporate',
	'fields' => array(
		array(
			'key' => 'field_638df0fc69587',
			'label' => 'Corporate',
			'name' => 'corporate',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_638df130997b8',
			'button_label' => 'Aggiungi Accordion',
			'acfe_field_group_condition' => 0,
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_638df130997b8',
					'label' => 'Accordion Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'acfe_field_group_condition' => 0,
					'parent_repeater' => 'field_638df0fc69587',
				),
				array(
					'key' => 'field_638df15b997b9',
					'label' => 'Accordion Content',
					'name' => 'content',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'default_value' => '',
					'acfe_wysiwyg_height' => 300,
					'acfe_wysiwyg_max_height' => '',
					'acfe_wysiwyg_valid_elements' => '',
					'acfe_wysiwyg_custom_style' => '',
					'acfe_wysiwyg_disable_wp_style' => 0,
					'acfe_wysiwyg_autoresize' => 0,
					'acfe_wysiwyg_disable_resize' => 0,
					'acfe_wysiwyg_remove_path' => 0,
					'acfe_wysiwyg_menubar' => 0,
					'acfe_wysiwyg_transparent' => 0,
					'acfe_wysiwyg_merge_toolbar' => 0,
					'acfe_wysiwyg_custom_toolbar' => 0,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'acfe_field_group_condition' => 0,
					'acfe_wysiwyg_auto_init' => 0,
					'acfe_wysiwyg_min_height' => 300,
					'acfe_wysiwyg_toolbar_buttons' => array(
					),
					'parent_repeater' => 'field_638df0fc69587',
				),
				array(
					'key' => 'field_638dfb193c8aa',
					'label' => 'Persons group',
					'name' => 'persons_group',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'block',
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_638df1c8997bc',
					'button_label' => 'Aggiungi Persons Group',
					'acfe_field_group_condition' => 0,
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_638df1c8997bc',
							'label' => 'Persons Title',
							'name' => 'persons_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'acfe_field_group_condition' => 0,
							'parent_repeater' => 'field_638dfb193c8aa',
						),
						array(
							'key' => 'field_638df18d997ba',
							'label' => 'Persons',
							'name' => 'persons',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'acfe_field_group_condition' => 0,
							'acfe_repeater_stylised_button' => 0,
							'layout' => 'block',
							'min' => 0,
							'max' => 0,
							'collapsed' => 'field_638df0fc6aaed',
							'button_label' => 'Aggiungi Riga',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_638df0fc6aaed',
									'label' => 'Person',
									'name' => 'person',
									'aria-label' => '',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'group_638dd774ab3a0',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
									'acfe_field_group_condition' => 0,
									'acfe_seamless_style' => 0,
									'acfe_clone_modal' => 0,
									'acfe_clone_modal_close' => 0,
									'acfe_clone_modal_button' => '',
									'acfe_clone_modal_size' => 'large',
									'parent_repeater' => 'field_638df18d997ba',
								),
							),
							'parent_repeater' => 'field_638dfb193c8aa',
						),
						array(
							'key' => 'field_638df1dc997bd',
							'label' => 'Downloads Title',
							'name' => 'downloads_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'acfe_field_group_condition' => 0,
							'parent_repeater' => 'field_638dfb193c8aa',
						),
						array(
							'key' => 'field_638df220997bf',
							'label' => 'Downloads',
							'name' => 'downloads',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'show_in_graphql' => 1,
							'clone' => array(
								0 => 'group_637661f463f62',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_field_group_condition' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
							'parent_repeater' => 'field_638dfb193c8aa',
						),
					),
					'parent_repeater' => 'field_638df0fc69587',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/governance-corporate.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'show_in_graphql' => 1,
	'graphql_field_name' => 'acfPages_gov_corporate',
	'map_graphql_types_from_location_rules' => 1,
	'graphql_types' => array(
		0 => 'Page',
		1 => 'Template_GovernanceCorporate',
	),
	'modified' => 1679906267,
));

endif;